CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'buyildir'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'buyildir'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';
